<?php

use App\Http\Controllers\Api\AinaController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\DhamanaController;
use App\Http\Controllers\Api\LoanController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\MiamalaController;
use App\Http\Controllers\Api\OfisiController;
use App\Http\Controllers\Api\TransactionChangeController;
use App\Http\Controllers\Api\UploadController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user', function (Request $request) {
        return $request->user();
    });
    Route::get('logWithAccessToken', [AuthController::class, 'logWithAccessToken']);
    Route::get('logout', [AuthController::class, 'logout']);
    Route::get('getOfisiData', [OfisiController::class, 'getOfisiData']);
    Route::post('sajiliMteja', [CustomerController::class, 'sajiliMteja']);
    Route::post('ondoaUnreadMeseji', [MessageController::class, 'ondoaUnreadMeseji']);
    Route::post('sajiliMakato', [AinaController::class, 'sajiliMakato']);
    Route::post('sajiliMkopo', [LoanController::class, 'sajiliMkopo']);
    Route::get('getMikopoMipya', [LoanController::class, 'getMikopoMipya']);
    Route::post('sajiliDhamana', [DhamanaController::class, 'sajiliDhamana']);
    Route::post('ondoaDhamana', [DhamanaController::class, 'ondoaDhamana']);
    Route::post('ombaPitishaMkopo', [LoanController::class, 'ombaPitishaMkopo']);
    Route::get('getMikopoPitisha', [LoanController::class, 'getMikopoPitisha']);
    Route::post('pitishaMkopo', [LoanController::class, 'pitishaMkopo']);
    Route::post('batilishaMkopo', [LoanController::class, 'batilishaMkopo']);
    Route::get('getMikopoKasoro', [LoanController::class, 'getMikopoKasoro']);
    Route::post('lipiaRejesho', [MiamalaController::class, 'lipiaRejesho']);
    Route::post('lipiaFaini', [MiamalaController::class, 'lipiaFaini']);
    Route::post('futaKato', [AinaController::class, 'futaKato']);
    Route::post('badiliUshirika', [OfisiController::class, 'badiliUshirika']);
    Route::get('getUserOfisiSummary', [OfisiController::class, 'getUserOfisiSummary']);
    Route::post('badiliOfisi', [OfisiController::class, 'badiliOfisi']);
    Route::post('sajiliOfisiBilaUser', [OfisiController::class, 'sajiliOfisiBilaUser']);
    Route::post('jiungeOfisiBilaUser', [OfisiController::class, 'jiungeOfisiBilaUser']);
    Route::get('getOfisiUsersWithDetails', [OfisiController::class, 'getOfisiUsersWithDetails']);
    Route::post('futaMtumishi', [OfisiController::class, 'futaMtumishi']);
    Route::post('badiliCheo', [OfisiController::class, 'badiliCheo']);
    Route::post('registerMtumishi', [AuthController::class, 'registerMtumishi']);
    Route::post('editMtumishi', [AuthController::class, 'editMtumishi']);
    Route::post('sajiliPato', [MiamalaController::class, 'sajiliPato']);
    Route::post('getMapato', [OfisiController::class, 'getMapato']);
    Route::post('getMatumizi', [OfisiController::class, 'getMatumizi']);
    Route::post('sajiliTumizi', [MiamalaController::class, 'sajiliTumizi']);
    Route::post('getMwamala', [OfisiController::class, 'getMwamala']);
    Route::post('haliliMwamala', [TransactionChangeController::class, 'haliliMwamala']);
    Route::post('kubaliMwamala', [TransactionChangeController::class, 'kubaliMwamala']);
    Route::post('kataaMwamala', [TransactionChangeController::class, 'kataaMwamala']);
    Route::post('futaMwamala', [TransactionChangeController::class, 'futaMwamala']);
    Route::post('futaMwamala', [TransactionChangeController::class, 'futaMwamala']);
    Route::post('kubaliKufutaMwamala', [TransactionChangeController::class, 'kubaliKufutaMwamala']);
    Route::post('kataaFutaMwamala', [TransactionChangeController::class, 'kataaFutaMwamala']);
    Route::get('getMarekebishoMiamala', [MiamalaController::class, 'getMarekebishoMiamala']);
    Route::get('getMiamalaByDay', [MiamalaController::class, 'getMiamalaByDay']);
    Route::post('getMiamalaByDates', [MiamalaController::class, 'getMiamalaByDates']);
    Route::post('haririMkopo', [LoanController::class, 'haririMkopo']);
    Route::post('fungaMkopo', [LoanController::class, 'fungaMkopo']);
    Route::post('getCustomerLoanDetails', [LoanController::class, 'getCustomerLoanDetails']);
    Route::post('haririMteja', [CustomerController::class, 'haririMteja']);
});

Route::post('/upload', [UploadController::class, 'uploadImage']);
Route::get('getOfisiByLocation', [OfisiController::class, 'getOfisiByLocation']);
Route::get('validateNewRegisterRequest', [AuthController::class, 'validateNewRegisterRequest']);
Route::get('validateOldRegisterRequest', [AuthController::class, 'validateOldRegisterRequest']);
Route::post('registerMtumishiNewOfisi', [AuthController::class, 'registerMtumishiNewOfisi']);
Route::post('registerMtumishiOldOfisi', [AuthController::class, 'registerMtumishiOldOfisi']);
Route::get('login', [AuthController::class, 'login']);
